### ISSUE TITLE
release a QGIS 3.22 version

### ISSUE THREAD

**Issue by tpo** [sourcepole/bbox#23]
Could you please release a QGIS 3.22 version?

Alternative 1: bookworm images
-------------------------------------------

I'd suggest upgrading the base image in the Dockefiles to the current Debian stable (bookworm). There are both rust and debian slim docker images available for bookworm.

Alternative 2: bullseye-backports images
------------------------------------------------------

Alternatively QGIS 3.22 is also in bullseye-stable: https://packages.debian.org/search?keywords=qgis

If you want to stay on bullseye then an alternative could be to use bullseye-backports. There is an official debian docker image based on bullseye-backports, however there is no bullseye-backports-slim: https://hub.docker.com/_/debian/tags?page=1&name=bullseye

However there are no bullseye-backports docker images for rust. Evindently I do not know how dependencies between Debian releases and Rust work, so the existence of a "backports" variant of Rust docker images might be a non-issue.

Alternative 3: adding the bullseye-backports repo during docker build
--------------------------------------------------------------------------------------------

The third alternative would be to add the bullseye-backports repo to /etc/apt/sources and install the qgis server from there.

Recommendation
------------------------

* Going with alternative 1 is the least work long term - at some point you'll need to update to bookworm anyway so you just as well might do all the work now.
* I'd estimate alternative 3 to be the least work short term, aka the quick hack.

I could certainly try to do a qgis_3.22_on_bullseye_backports branch if you'd think that would be helpful and the way to go.

I'm not sure I'd be able to sort out Rusty conflicts when - this is what I expect to happen - moving to a major new Rust version or a jump in the C-bindings (I'm guessing that this is the case) that come with bookworm.

Open questions
---------------------

In case I'd go with the qgis_3.22_on_bullseye_backports branch then I have no clue how production ready the current HEAD is. Should I be forking on the [v2023.03.14.01](https://github.com/sourcepole/bbox/releases/tag/v2023.03.14.01) tag then instead?

Feedback wellcome. Thanks.

**Comment by HusseinKabbout** [comment]
Here is the release with QGIS 3.32 --> [v0.5.0-alpha2](https://github.com/sourcepole/bbox/releases/tag/v0.5.0-alpha2)
